# version: "3"
# services:
#   flask:
#     image: yolov5-flask:latest
#     ports:
#       - 5000:5000
#     restart: unless-stopped
#     volumes:
#       - ./yolov5-flask:/app.py
#       - ./yolov5-flask/templates:/templates

# build Image from Docker Hub
version: "3"
services:
    flask:
      image: yolov5-flask
      # build: .
      stdin_open: true
      tty: true
      ports:
        - 5000:5000
      ipc: host
      privileged: true
      volumes:
        - /home/stannyho/Documents/yolov5-flask:/workspace


