# build Image from Docker Hub
version: "3"
services:
    flask:
      image: stanny880913/yolov5-flask 
      # build: .
      stdin_open: true
      tty: true
      ports:
        - 5000:5000
      ipc: host
      privileged: true
      volumes:
        - .:/workspace


